django_demo/mysite/mysite/urls.py
#       """mysite URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/2.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('website_tools/', include('website_tools.urls')),
                  path('game/', include('game.ulrs')),
                  path('website_useful/', include('website_useful.urls')),
                  path('yuner/', include('yuner.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_demo/mysite/website_tools/urls.py
from django.urls import path
from . import views

app_name='website_tools'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/result/', views.ResultView.as_view(), name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

django_demo/mysite/website_useful/urls.py
from django.urls import path
from . import views

app_name = 'game'
urlpatterns = [
    path('', views.get_Category, name='category')
]

django_demo/mysite/yuner/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('upload_img',views.upload_img,name='upload_img')
]

django_demo/mysite/game/models.py
from django.db import models


# Create your models here.

class Game_5566(models.Model):
    num = models.CharField(max_length=30, verbose_name='ID号')
    game_title = models.CharField(max_length=150, verbose_name='游戏名称')

    def __str__(self):
        return self.game_title

django_demo/mysite/website_tools/models.py
import datetime
import time

from django.db import models

# Create your models here.
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200, verbose_name='问题')
    pub_date = models.DateTimeField('发布时间')

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question_text = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='选择问题')
    choice_tex = models.CharField(max_length=200, verbose_name='新增选项')
    votes = models.IntegerField(default=0, verbose_name='票数')

    def __str__(self):
        return self.choice_tex

django_demo/mysite/website_useful/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=100, verbose_name='类别')


class UrlTools(models.Model):
    title = models.CharField(max_length=100)
    url_link = models.CharField(max_length=100)
    # category = models.ForeignKey(to=Category,on_delete=models.CASCADE)

django_demo/mysite/yuner/models.py
from django.db import models


# Create your models here.

class Img(models.Model):
    img_url = models.ImageField(upload_to='image')

django_demo/mysite/game/views.py
from django.shortcuts import render
from django.views import generic
from game.models import Game_5566


# Create your views here.

def get_5566(request):
    pattern = request.GET.get('pattern')
    if pattern != None and pattern != '':
        game_list = Game_5566.objects.filter(game_title__contains=pattern)
        if game_list.count() != 0:
            return render(request, 'game/game.html', context={"game_list": game_list})
        else:
            not_exist_message = '你查找的不存在'
            return render(request, 'game/game.html', context={'not_exist_message': not_exist_message})
    return render(request, 'game/game.html')

django_demo/mysite/website_tools/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from website_tools.models import Question, Choice


# Create your views here.

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('website/index.html')
#     context = {
#         'latest_question_list': latest_question_list
#     }
#     return HttpResponse(template.render(context, request))
class IndexView(generic.ListView):
    template_name = 'website/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, template_name='website/detail.html', context={'question': question})
class DetailView(generic.DetailView):
    template_name = 'website/detail.html'
    model = Question


# def result(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'website/result.html', context={'question': question})

class ResultView(generic.DetailView):
    template_name = 'website/result.html'
    model = Question


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'website/detail.html', {'question': question, 'errormessage': '你没有选择选项'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('website_tools:result', args=(question.id,)))

django_demo/mysite/website_useful/views.py
from django.shortcuts import render
from website_useful.models import Category, UrlTools


# Create your views here.

def get_Category(request):
    return render(request, "website_useful/category.html")

django_demo/mysite/yuner/views.py
from django.shortcuts import render
from yuner.models import Img


# Create your views here.

def upload_img(request):
    if request.method == 'post':
        file_list = request.FILES.getlist()
        for file in file_list:
            img = Img(img_url=file)
            img.save()
    return render(request, 'yuner/upload_img.html')

django_demo/mysite/game/templates/game/game.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>game</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width,
                                     initial-scale=1.0,
                                     maximum-scale=1.0,
                                     user-scalable=no">
    <link rel="stylesheet" href="{% static 'game/form_css.css' %}">
</head>
<body>
<br>
<br>
<form action="{% url 'game:5566' %}" method="get">
    {% csrf_token %}
    <label for="pattern">查询</label>
    <input name="pattern" id="pattern">
    <input type="submit">
</form>
<br>
{% if game_list %}
    <ul class="list-group">
        {% for game in game_list %}
            <li class="list-group-item"><a href="http://www.soft5566.com/down/{{ game.num }}-1.html" class="list-group-item">{{ game.game_title }}</a></li>
        {% endfor %}
    </ul>
{% endif %}
{% if not_exist_message %}
    <p>你要查找的不存在</p>
{% endif %}
</body>
</html>

django_demo/mysite/website_tools/templates/website/detail.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{% if errormessage %}
    <p><strong>{{ errormessage }}</strong></p>
{% endif %}
<form action="{% url 'website_tools:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_tex }}</label>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
</body>
</html>

django_demo/mysite/website_tools/templates/website/index.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>问题列表</title>
</head>
<body>

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'website_tools:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>没有问题需要投票</p>
{% endif %}
</body>
</html>

django_demo/mysite/website_tools/templates/website/result.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>投票结果</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.tex }}------{{ choice.votes }}票</li>
    {% endfor %}
</ul>
<a href="{% url 'website_tools:detail' question.id %}">重新投票</a>
</body>
</html>

django_demo/mysite/website_useful/templates/website_useful/category.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>网页类别</title>
</head>
<body>
    <form>

    </form>
</body>
</html>

django_demo/mysite/yuner/templates/yuner/upload_img.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>上传照片</title>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" multiple="">
        <input type="submit" value="上传">
    </form>
</body>
</html>